// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/auth/auto/page.tsx
{
  const handler = {} as typeof import("../../app/auth/auto/page.js")
  handler satisfies AppPageConfig<"/auth/auto">
}

// Validate ../../app/auth/login/page.tsx
{
  const handler = {} as typeof import("../../app/auth/login/page.js")
  handler satisfies AppPageConfig<"/auth/login">
}

// Validate ../../app/my/page.tsx
{
  const handler = {} as typeof import("../../app/my/page.js")
  handler satisfies AppPageConfig<"/my">
}

// Validate ../../app/new/page.tsx
{
  const handler = {} as typeof import("../../app/new/page.js")
  handler satisfies AppPageConfig<"/new">
}

// Validate ../../app/page.tsx
{
  const handler = {} as typeof import("../../app/page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ../../app/api/logout/route.ts
{
  const handler = {} as typeof import("../../app/api/logout/route.js")
  handler satisfies RouteHandlerConfig<"/api/logout">
}

// Validate ../../app/api/submissions/[id]/route.ts
{
  const handler = {} as typeof import("../../app/api/submissions/[id]/route.js")
  handler satisfies RouteHandlerConfig<"/api/submissions/[id]">
}

// Validate ../../app/api/submissions/list/route.ts
{
  const handler = {} as typeof import("../../app/api/submissions/list/route.js")
  handler satisfies RouteHandlerConfig<"/api/submissions/list">
}

// Validate ../../app/api/submissions/route.ts
{
  const handler = {} as typeof import("../../app/api/submissions/route.js")
  handler satisfies RouteHandlerConfig<"/api/submissions">
}

// Validate ../../app/auth/callback/route.ts
{
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  handler satisfies RouteHandlerConfig<"/auth/callback">
}

// Validate ../../app/auth/google/route.ts
{
  const handler = {} as typeof import("../../app/auth/google/route.js")
  handler satisfies RouteHandlerConfig<"/auth/google">
}





// Validate ../../app/layout.tsx
{
  const handler = {} as typeof import("../../app/layout.js")
  handler satisfies LayoutConfig<"/">
}
