var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/auth/google/route.js")
R.c("server/chunks/node_modules_@supabase_node-fetch_lib_index_d6dc7176.js")
R.c("server/chunks/node_modules_next_7b6b5450._.js")
R.c("server/chunks/node_modules_tr46_3e4df63f._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_0e404d3a._.js")
R.c("server/chunks/node_modules_fbb1f292._.js")
R.c("server/chunks/[root-of-the-server]__4fe5b7e9._.js")
R.m("[project]/.next-internal/server/app/auth/google/route/actions.js [app-rsc] (server actions loader, ecmascript)")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/auth/google/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/auth/google/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
